"""Seed the components_library + control_board_library with a comprehensive
starter catalog of Pi-family-compatible hardware. Idempotent — skips files
that already exist. Run once: `python3 tools/seed_catalog.py`.

Each manifest validates against shared_schemas/manifest_schema.json. The
catalog covers the most common market hardware so the device-registration
wizard has rich pickers from day one. Image URLs in metadata point at
public Wikimedia / manufacturer assets — placeholders the operator can
swap for site-specific photos later.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
COMPONENTS_DIR = REPO_ROOT / "libraries" / "components_library" / "manifests"
BOARDS_DIR = REPO_ROOT / "libraries" / "control_board_library" / "manifests"


# ─── Components ─────────────────────────────────────────────────────────────
COMPONENTS: list[dict] = [
    # ── Temperature / environment ─────────────────────────────────────────
    {
        "stable_id": "sensor.temp_humid.dht22",
        "name": "DHT22 / AM2302 Temperature & Humidity Sensor",
        "vendor": "Aosong",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "environment",
        "description": "Digital temperature (-40~80°C, ±0.5°C) + humidity (0-100% RH, ±2%) on a single wire. Slow (1Hz max) but accurate. Industry standard for HVAC, greenhouses, climate monitoring.",
        "tags": ["temperature", "humidity", "1-wire-style", "low-power"],
        "capabilities": ["temperature_read", "humidity_read"],
        "interfaces": [{"type": "GPIO", "direction": "bidir", "pins_required": 1, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 1.5, "current_ma_peak": 2.5, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5", "compute.rpi_zero_2_w"],
        "drivers_micropython": [{"module": "dht", "version_range": ">=0.1.0"}],
        "image_url": "https://www.adafruit.com/product/393",
        "datasheet_url": "https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf",
        "wiring_diagram_url": "https://learn.adafruit.com/dht/wiring",
        "brand_variants": ["Aosong AM2302", "DFRobot DHT22", "Adafruit 393"],
        "price_usd_range": [3, 12],
    },
    {
        "stable_id": "sensor.temp_humid.dht11",
        "name": "DHT11 Temperature & Humidity Sensor",
        "vendor": "Aosong",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "environment",
        "description": "Budget single-wire digital temp (0~50°C, ±2°C) + humidity (20-90% RH, ±5%). Less accurate than DHT22; pick when cost matters and tight tolerance doesn't.",
        "tags": ["temperature", "humidity", "budget"],
        "capabilities": ["temperature_read", "humidity_read"],
        "interfaces": [{"type": "GPIO", "direction": "bidir", "pins_required": 1, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.5, "current_ma_peak": 1.5, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "dht", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/DHT11-Module.jpg/640px-DHT11-Module.jpg",
        "datasheet_url": "https://www.mouser.com/datasheet/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf",
        "brand_variants": ["Aosong DHT11", "KY-015 module", "HiLetGo DHT11"],
        "price_usd_range": [1, 4],
    },
    {
        "stable_id": "sensor.env.bme280",
        "name": "BME280 Temp / Humidity / Pressure Sensor",
        "vendor": "Bosch Sensortec",
        "version": "1.1.0",
        "category": "sensors", "subcategory": "environment",
        "description": "Three-in-one combined sensor over I2C/SPI. Temp ±1°C, humidity ±3% RH, pressure ±1hPa. Tiny, low-power (~3µA), high accuracy. Industry workhorse for weather stations + indoor air quality.",
        "tags": ["temperature", "humidity", "pressure", "altitude", "i2c", "spi", "bosch"],
        "capabilities": ["temperature_read", "humidity_read", "pressure_read", "altitude_compute"],
        "interfaces": [
            {"type": "I2C", "direction": "bidir", "address": "0x76 or 0x77", "speed_hz": 400000, "voltage": 3.3},
            {"type": "SPI", "direction": "bidir", "voltage": 3.3},
        ],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.4, "current_ma_peak": 0.7, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "bme280", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/BME280_Sensor_Front.jpg/640px-BME280_Sensor_Front.jpg",
        "datasheet_url": "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf",
        "brand_variants": ["Bosch BME280", "Adafruit 2652", "GY-BME280"],
        "price_usd_range": [5, 18],
    },
    {
        "stable_id": "sensor.temp.max31855_k",
        "name": "MAX31855 K-Type Thermocouple Amplifier",
        "vendor": "Maxim/Analog Devices",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "temperature",
        "description": "K-type thermocouple cold-junction-compensated SPI amplifier. -270~1372°C, 0.25°C resolution. Use for high-temperature process control (kilns, ovens, furnaces, food production).",
        "tags": ["temperature", "thermocouple", "k-type", "spi", "high-temp"],
        "capabilities": ["temperature_read"],
        "interfaces": [{"type": "SPI", "direction": "in", "voltage": 3.3, "speed_hz": 5000000}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.9, "current_ma_peak": 1.5, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "max31855", "version_range": ">=0.1.0"}],
        "image_url": "https://cdn-shop.adafruit.com/970x728/269-00.jpg",
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf",
        "brand_variants": ["Adafruit 269", "Maxim MAX31855KASA"],
        "price_usd_range": [12, 25],
        "safety_class": "critical",
    },
    {
        "stable_id": "sensor.temp.ir_mlx90614",
        "name": "MLX90614 Non-Contact IR Temperature Sensor",
        "vendor": "Melexis",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "temperature",
        "description": "Non-contact infrared thermometer over I2C. Object temp -70~380°C, ±0.5°C in human-body range. Used for contactless surface temperature, body temp screening, hot-surface alarms.",
        "tags": ["temperature", "infrared", "non-contact", "i2c"],
        "capabilities": ["temperature_read"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x5A", "speed_hz": 100000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 1.5, "current_ma_peak": 2.5, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "mlx90614", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/MLX90614_Module.jpg/480px-MLX90614_Module.jpg",
        "datasheet_url": "https://www.melexis.com/-/media/files/documents/datasheets/mlx90614-datasheet-melexis.pdf",
        "brand_variants": ["GY-906 module", "Adafruit 1747"],
        "price_usd_range": [8, 25],
    },

    # ── Distance / position / motion ──────────────────────────────────────
    {
        "stable_id": "sensor.distance.hcsr04",
        "name": "HC-SR04 Ultrasonic Distance Sensor",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "distance",
        "description": "Ultrasonic time-of-flight rangefinder. 2cm-400cm, ±3mm. Trigger pulse → echo pulse-width. Used for tank level, presence detection, robot collision avoidance.",
        "tags": ["distance", "ultrasonic", "rangefinder"],
        "capabilities": ["distance_read"],
        "interfaces": [{"type": "GPIO", "direction": "bidir", "pins_required": 2, "voltage": 5.0,
                        "notes": "Echo needs level shift to 3.3V — use 1k/2k divider on Pi/Pico"}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 15, "current_ma_peak": 30, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ultrasonic-Sensor-HC-SR04.jpg/640px-Ultrasonic-Sensor-HC-SR04.jpg",
        "datasheet_url": "https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf",
        "wiring_diagram_url": "https://www.electronicwings.com/raspberry-pi/raspberry-pi-and-ultrasonic-distance-sensor-hc-sr04",
        "brand_variants": ["Elegoo HC-SR04", "HiLetGo HC-SR04", "JSN-SR04T (waterproof variant)"],
        "price_usd_range": [1, 5],
    },
    {
        "stable_id": "sensor.motion.pir_hcsr501",
        "name": "HC-SR501 PIR Motion Sensor",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "motion",
        "description": "Passive infrared motion detector with adjustable sensitivity + hold time. ~7m range, 120° cone. Used for security lights, presence-aware automation, idle-mode triggers.",
        "tags": ["motion", "pir", "infrared"],
        "capabilities": ["motion_detect"],
        "interfaces": [{"type": "GPIO", "direction": "out", "pins_required": 1, "voltage": 3.3}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 0.06, "current_ma_peak": 0.1, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/PIR_Sensor_HC-SR501.jpg/640px-PIR_Sensor_HC-SR501.jpg",
        "datasheet_url": "https://www.mpja.com/download/31227sc.pdf",
        "brand_variants": ["HC-SR501", "AM312 mini-PIR", "Panasonic EKMC"],
        "price_usd_range": [1, 6],
    },
    {
        "stable_id": "sensor.imu.mpu6050",
        "name": "MPU6050 6-Axis IMU (Gyro + Accelerometer)",
        "vendor": "InvenSense / TDK",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "imu",
        "description": "Triple-axis gyro (±250-2000°/s) + triple-axis accelerometer (±2-16g) on I2C. On-chip motion processor (DMP) handles sensor fusion. Used for tilt sensing, vibration monitoring, robotics.",
        "tags": ["imu", "gyroscope", "accelerometer", "i2c"],
        "capabilities": ["acceleration_read", "rotation_read", "tilt_read"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x68 or 0x69", "speed_hz": 400000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 3.9, "current_ma_peak": 6, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "mpu6050", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/MPU-6050_Module.jpg/640px-MPU-6050_Module.jpg",
        "datasheet_url": "https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf",
        "brand_variants": ["GY-521 module", "Adafruit 3886", "InvenSense MPU-6050"],
        "price_usd_range": [2, 8],
    },

    # ── Light ─────────────────────────────────────────────────────────────
    {
        "stable_id": "sensor.light.bh1750",
        "name": "BH1750 Ambient Light Sensor",
        "vendor": "Rohm",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "light",
        "description": "Digital ambient light sensor with built-in 16-bit ADC, 1-65535 lux range over I2C. Cheap, accurate replacement for photoresistor + ADC combos.",
        "tags": ["light", "lux", "i2c"],
        "capabilities": ["light_read"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x23 or 0x5C", "speed_hz": 100000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.12, "current_ma_peak": 0.19, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "bh1750", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/BH1750_Light_Sensor.jpg/640px-BH1750_Light_Sensor.jpg",
        "datasheet_url": "https://www.mouser.com/datasheet/2/348/bh1750fvi-e-186247.pdf",
        "brand_variants": ["GY-302 module", "Rohm BH1750FVI"],
        "price_usd_range": [1, 5],
    },

    # ── Time / clock ──────────────────────────────────────────────────────
    {
        "stable_id": "sensor.rtc.ds3231",
        "name": "DS3231 Precision Real-Time Clock",
        "vendor": "Maxim/Analog Devices",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "rtc",
        "description": "Temperature-compensated crystal oscillator RTC over I2C, ±2 ppm accuracy. CR2032-backed time when main power is off. Essential for offline timestamping in disconnected edge sites.",
        "tags": ["rtc", "clock", "i2c", "battery-backed"],
        "capabilities": ["time_read", "time_write", "alarm_set"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x68", "speed_hz": 400000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.3, "current_ma_peak": 0.5, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "ds3231", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/DS3231_RTC_Module.jpg/640px-DS3231_RTC_Module.jpg",
        "datasheet_url": "https://datasheets.maximintegrated.com/en/ds/DS3231.pdf",
        "brand_variants": ["Adafruit 3013", "Generic ZS-042 module"],
        "price_usd_range": [2, 10],
    },

    # ── Current / power ───────────────────────────────────────────────────
    {
        "stable_id": "sensor.current.acs712_30a",
        "name": "ACS712 Hall-Effect Current Sensor (30A)",
        "vendor": "Allegro Microsystems",
        "version": "1.0.0",
        "category": "sensors", "subcategory": "current",
        "description": "Galvanically isolated bidirectional current sensor, ±30A range, analog output 66mV/A. Needs ADC. Used for AC/DC current monitoring on machinery, motor over-current detection.",
        "tags": ["current", "hall-effect", "analog", "isolation"],
        "capabilities": ["current_read"],
        "interfaces": [{"type": "ADC", "direction": "in", "pins_required": 1, "voltage": 5.0,
                        "notes": "Pico ADC tops out at 3.3V — use a divider or ACS712-5A 185mV/A variant for direct Pico connection."}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 10, "current_ma_peak": 13, "power_source": "external"},
        "compute": ["compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/ACS712_Module.jpg/640px-ACS712_Module.jpg",
        "datasheet_url": "https://www.allegromicro.com/-/media/files/datasheets/acs712-datasheet.pdf",
        "brand_variants": ["ACS712ELC-05B (5A)", "ACS712ELC-20A", "ACS712ELC-30A", "ACS758 (50-200A successor)"],
        "price_usd_range": [2, 8],
        "safety_class": "advisory",
    },

    # ── Servos / motors ───────────────────────────────────────────────────
    {
        "stable_id": "actuator.servo.sg90",
        "name": "SG90 Micro Servo (9g)",
        "vendor": "TowerPro",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "servo",
        "description": "Tiny 9g hobby servo, 180° range, 1.8kg·cm torque, PWM-controlled (50Hz, 1-2ms pulse). Use for small flaps, dampers, light gates. Plastic gears — NOT for continuous load.",
        "tags": ["servo", "9g", "hobby"],
        "capabilities": ["position_set"],
        "interfaces": [{"type": "PWM", "direction": "in", "pins_required": 1, "speed_hz": 50, "voltage": 5.0}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 250, "current_ma_peak": 700, "power_source": "external",
                  },
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/TowerPro_SG90_servo_motor.jpg/640px-TowerPro_SG90_servo_motor.jpg",
        "datasheet_url": "http://www.ee.ic.ac.uk/pcheung/teaching/DE1_EE/stores/sg90_datasheet.pdf",
        "brand_variants": ["TowerPro SG90", "Miuzei MS18", "Generic SG90"],
        "price_usd_range": [1, 5],
    },
    {
        "stable_id": "actuator.servo.mg996r",
        "name": "MG996R Metal-Gear Servo",
        "vendor": "TowerPro",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "servo",
        "description": "Metal-gear high-torque servo, 180° range, 9.4-11kg·cm torque @ 6V. PWM-controlled. Workhorse for robotics, pan-tilt rigs, automated valves, garage door rotation.",
        "tags": ["servo", "metal-gear", "high-torque"],
        "capabilities": ["position_set"],
        "interfaces": [{"type": "PWM", "direction": "in", "pins_required": 1, "speed_hz": 50, "voltage": 6.0}],
        "power": {"voltage_v": 6.0, "voltage_tolerance_pct": 10, "current_ma_typical": 500, "current_ma_peak": 2500, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Servo_Motor_MG996R.jpg/640px-Servo_Motor_MG996R.jpg",
        "datasheet_url": "https://www.electronicoscaldas.com/datasheet/MG996R_Tower-Pro.pdf",
        "brand_variants": ["TowerPro MG996R", "Hiwonder LD-1501MG", "MG995 (cheaper sibling)"],
        "price_usd_range": [3, 12],
    },
    {
        "stable_id": "actuator.stepper.28byj48",
        "name": "28BYJ-48 5V Stepper Motor (with ULN2003 driver)",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "stepper",
        "description": "Tiny geared unipolar stepper, 4096 steps/rev (gearbox 1:64), 5V, ~0.3kg·cm. Always sold with ULN2003 driver board. Perfect for light positioning: blinds, dispensers, small dampers.",
        "tags": ["stepper", "unipolar", "geared", "low-cost"],
        "capabilities": ["position_step", "rotation_continuous"],
        "interfaces": [{"type": "GPIO", "direction": "out", "pins_required": 4, "voltage": 5.0}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 160, "current_ma_peak": 240, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Stepper_motor_28BYJ-48_with_ULN2003_driver.jpg/640px-Stepper_motor_28BYJ-48_with_ULN2003_driver.jpg",
        "datasheet_url": "https://components101.com/sites/default/files/component_datasheet/28byj48-step-motor-datasheet.pdf",
        "brand_variants": ["Generic 28BYJ-48", "Elegoo 28BYJ-48", "Kuman 5V Stepper"],
        "price_usd_range": [2, 6],
    },
    {
        "stable_id": "actuator.stepper.nema17",
        "name": "NEMA 17 Stepper Motor",
        "vendor": "Generic / Various",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "stepper",
        "description": "Bipolar industrial stepper, 1.8° step (200/rev), holding torque 40-60 N·cm typical, ~1-2A per phase. Needs a current-limited driver (A4988, DRV8825, TMC2209). Standard for 3D printers, CNC, conveyors, precision dispensers.",
        "tags": ["stepper", "bipolar", "industrial", "nema17"],
        "capabilities": ["position_step", "rotation_continuous"],
        "interfaces": [{"type": "GPIO", "direction": "in", "pins_required": 0, "notes": "Drive via A4988/DRV8825/TMC2209 — see board.stepper.* entries"}],
        "power": {"voltage_v": 12.0, "voltage_tolerance_pct": 25, "current_ma_typical": 800, "current_ma_peak": 2000, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Nema17_stepper_motor.jpg/640px-Nema17_stepper_motor.jpg",
        "datasheet_url": "https://www.makerguides.com/wp-content/uploads/2019/03/nema17.pdf",
        "brand_variants": ["StepperOnline 17HS19-2004S1", "Polulu #2267", "Wantai 42BYGHW609", "OMC Stepperonline"],
        "price_usd_range": [10, 30],
        "safety_class": "advisory",
    },

    # ── Relays / power switching ──────────────────────────────────────────
    {
        "stable_id": "actuator.relay.5v_spdt",
        "name": "5V SPDT Relay Module (single channel)",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "relay",
        "description": "Single SRD-05VDC-SL-C relay on a breakout with opto-isolator + driver transistor. Switches up to 10A 250VAC / 30VDC. Gold-standard switch for AC loads, heaters, fans, solenoid valves.",
        "tags": ["relay", "spdt", "opto-isolated", "mains"],
        "capabilities": ["switch_load"],
        "interfaces": [{"type": "GPIO", "direction": "in", "pins_required": 1, "voltage": 3.3, "notes": "Active-low on most modules"}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 70, "current_ma_peak": 90, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Relay-module-5v-1ch.jpg/640px-Relay-module-5v-1ch.jpg",
        "datasheet_url": "https://www.songle.com/eg/pdf/SRD%20Series%20RELAYS.pdf",
        "brand_variants": ["SunFounder 1-CH 5V", "Keyestudio Relay", "Elegoo Relay Module"],
        "price_usd_range": [1, 5],
        "safety_class": "critical",
    },
    {
        "stable_id": "actuator.solenoid.12v",
        "name": "12V Solenoid Valve (Plastic, 1/2 inch)",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "valve",
        "description": "Normally-closed plastic solenoid valve, 1/2\" NPS, 0.02-0.8 MPa, 500ms response. 12V DC ~500mA. Drive via relay or MOSFET. Use for irrigation, water dosing, beverage filling.",
        "tags": ["solenoid", "valve", "water", "12v"],
        "capabilities": ["valve_open", "valve_close"],
        "interfaces": [{"type": "GPIO", "direction": "in", "pins_required": 1, "voltage": 3.3, "notes": "Drive via relay/MOSFET — never directly from a GPIO pin"}],
        "power": {"voltage_v": 12.0, "voltage_tolerance_pct": 10, "current_ma_typical": 500, "current_ma_peak": 800, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Plastic_Solenoid_Valve_12V.jpg/640px-Plastic_Solenoid_Valve_12V.jpg",
        "brand_variants": ["U.S. Solid USS2-00002", "Generic 1/2\" NPS NC", "Adafruit 996"],
        "price_usd_range": [5, 20],
        "safety_class": "advisory",
    },
    {
        "stable_id": "actuator.pump.peristaltic_12v",
        "name": "12V DC Peristaltic Pump",
        "vendor": "Kamoer / Generic",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "pump",
        "description": "Self-priming peristaltic pump, 5-100 mL/min, food-grade silicone tube. Drive via MOSFET or motor driver. Common in hydroponic dosing, lab dispensing, fish-tank water-change automation.",
        "tags": ["pump", "peristaltic", "dosing", "food-grade"],
        "capabilities": ["fluid_dispense"],
        "interfaces": [{"type": "PWM", "direction": "in", "pins_required": 1, "voltage": 3.3,
                        "notes": "Drive via L298N or similar — pump motor pulls more than a GPIO can source"}],
        "power": {"voltage_v": 12.0, "voltage_tolerance_pct": 15, "current_ma_typical": 80, "current_ma_peak": 200, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Peristaltic_Pump_Module.jpg/640px-Peristaltic_Pump_Module.jpg",
        "brand_variants": ["Kamoer KPP", "Adafruit 1150", "Generic ZJchao"],
        "price_usd_range": [10, 35],
    },

    # ── Displays ──────────────────────────────────────────────────────────
    {
        "stable_id": "display.oled.ssd1306",
        "name": "SSD1306 OLED Display (0.96\" 128×64 I2C)",
        "vendor": "Solomon Systech",
        "version": "1.0.0",
        "category": "displays", "subcategory": "oled",
        "description": "Tiny monochrome OLED, 128×64 px, I2C or SPI. High contrast, low power, no backlight. Used for local status pages, IP-address display, recipe step preview.",
        "tags": ["oled", "display", "i2c"],
        "capabilities": ["display_text", "display_graphics"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x3C or 0x3D", "speed_hz": 400000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 8, "current_ma_peak": 20, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "drivers_micropython": [{"module": "ssd1306", "version_range": ">=0.1.0"}],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/OLED_Display_SSD1306.jpg/640px-OLED_Display_SSD1306.jpg",
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf",
        "brand_variants": ["Adafruit 326", "DiyMall 0.96 OLED", "Hosyond 4-pin OLED"],
        "price_usd_range": [3, 10],
    },
    {
        "stable_id": "display.lcd.16x2_i2c",
        "name": "16×2 Character LCD with PCF8574 I2C Backpack",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "displays", "subcategory": "character_lcd",
        "description": "Classic 16-column × 2-row HD44780 LCD with I2C backpack. Backlit. Trivial to drive (no parallel pin sprawl). Used for control panels, recipe-step display, alarm banners.",
        "tags": ["lcd", "character", "i2c", "hd44780"],
        "capabilities": ["display_text"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x27 or 0x3F", "speed_hz": 100000, "voltage": 5.0}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 25, "current_ma_peak": 40, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/16x2_LCD_module.jpg/640px-16x2_LCD_module.jpg",
        "datasheet_url": "https://www.sparkfun.com/datasheets/LCD/HD44780.pdf",
        "brand_variants": ["SunFounder LCD2004 (20x4 sibling)", "Generic 1602A", "Elegoo LCD1602"],
        "price_usd_range": [3, 12],
    },

    # ── Indicators / outputs ──────────────────────────────────────────────
    {
        "stable_id": "actuator.led_strip.ws2812b",
        "name": "WS2812B Addressable RGB LED Strip (NeoPixel)",
        "vendor": "Worldsemi",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "led",
        "description": "5V individually addressable RGB LEDs, single data line. ~60mA per LED at full white. Use for status walls, alarm banners, machine state visualization.",
        "tags": ["led", "rgb", "neopixel", "addressable"],
        "capabilities": ["display_color", "alarm_visual"],
        "interfaces": [{"type": "GPIO", "direction": "out", "pins_required": 1, "voltage": 5.0,
                        "notes": "Needs strict 800kHz timing — use PIO on Pico or rpi_ws281x on Pi"}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 5, "current_ma_typical": 600, "current_ma_peak": 6000, "power_source": "external",
                  },
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/WS2812B_LED_strip.jpg/640px-WS2812B_LED_strip.jpg",
        "datasheet_url": "https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf",
        "brand_variants": ["Adafruit NeoPixel", "BTF-LIGHTING WS2812B", "Worldsemi WS2812B"],
        "price_usd_range": [5, 40],
    },
    {
        "stable_id": "actuator.buzzer.passive_5v",
        "name": "Passive Piezo Buzzer (5V)",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "actuators", "subcategory": "audio",
        "description": "Passive piezo buzzer driven by PWM. Tone is set by PWM frequency. Used for audible alarms, button-press feedback, oven-done chime.",
        "tags": ["buzzer", "alarm", "audio"],
        "capabilities": ["alarm_audio", "tone_play"],
        "interfaces": [{"type": "PWM", "direction": "in", "pins_required": 1, "voltage": 3.3}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 20, "current_ma_typical": 30, "current_ma_peak": 50, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Piezo_Buzzer.jpg/640px-Piezo_Buzzer.jpg",
        "brand_variants": ["Generic passive piezo", "PUI Audio AT-1224-TT-R", "KY-006 module"],
        "price_usd_range": [1, 4],
    },
]


# ─── Control boards ─────────────────────────────────────────────────────────
BOARDS: list[dict] = [
    {
        "stable_id": "board.motor.l293d",
        "name": "L293D Dual H-Bridge Motor Driver",
        "vendor": "Texas Instruments",
        "version": "1.0.0",
        "category": "motor_drivers", "subcategory": "h_bridge",
        "description": "Classic dual quadruple half-H driver, drives two DC motors at up to 600mA per channel (1.2A peak). Cheaper and smaller than L298N but lower current. Use for small toys, low-power pumps.",
        "tags": ["motor_driver", "h_bridge", "dc"],
        "capabilities": ["dc_motor_drive", "stepper_drive_bipolar"],
        "interfaces": [
            {"type": "GPIO", "direction": "in", "pins_required": 2, "voltage": 3.3, "notes": "EN + DIR per motor"},
            {"type": "PWM", "direction": "in", "pins_required": 2, "voltage": 3.3, "notes": "Speed control via EN"},
        ],
        "power": {"voltage_v": 12.0, "voltage_tolerance_pct": 50, "current_ma_typical": 600, "current_ma_peak": 1200, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/L293D_Motor_Driver_IC.jpg/480px-L293D_Motor_Driver_IC.jpg",
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/l293.pdf",
        "brand_variants": ["TI L293D", "STMicro L293D", "DIY shield variants"],
        "price_usd_range": [2, 8],
    },
    {
        "stable_id": "board.motor.tb6612fng",
        "name": "TB6612FNG Dual DC Motor Driver",
        "vendor": "Toshiba",
        "version": "1.0.0",
        "category": "motor_drivers", "subcategory": "h_bridge",
        "description": "Modern, efficient (no big diode drop) dual H-bridge, 1.2A continuous / 3A peak per channel. Use instead of L298N for higher efficiency and cooler operation. Common in line followers, small robots.",
        "tags": ["motor_driver", "h_bridge", "efficient"],
        "capabilities": ["dc_motor_drive", "stepper_drive_bipolar"],
        "interfaces": [
            {"type": "GPIO", "direction": "in", "pins_required": 4, "voltage": 3.3, "notes": "IN1/IN2 per motor + STBY"},
            {"type": "PWM", "direction": "in", "pins_required": 2, "voltage": 3.3},
        ],
        "power": {"voltage_v": 6.0, "voltage_tolerance_pct": 50, "current_ma_typical": 1200, "current_ma_peak": 3000, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/TB6612FNG_module.jpg/640px-TB6612FNG_module.jpg",
        "datasheet_url": "https://www.sparkfun.com/datasheets/Robotics/TB6612FNG.pdf",
        "brand_variants": ["SparkFun ROB-14451", "Pololu #713", "Adafruit 2448"],
        "price_usd_range": [4, 12],
    },
    {
        "stable_id": "board.stepper.a4988",
        "name": "A4988 Stepper Motor Driver",
        "vendor": "Allegro Microsystems",
        "version": "1.0.0",
        "category": "motor_drivers", "subcategory": "stepper",
        "description": "Microstepping bipolar stepper driver, up to 35V / 2A per phase with heatsink. 1/16 microstep modes. Standard in RepRap 3D printers, small CNC. Pair with NEMA 17.",
        "tags": ["stepper", "microstepping", "a4988", "3d_printer"],
        "capabilities": ["stepper_drive_bipolar"],
        "interfaces": [
            {"type": "GPIO", "direction": "in", "pins_required": 2, "voltage": 5.0, "notes": "STEP + DIR"},
            {"type": "GPIO", "direction": "in", "pins_required": 3, "voltage": 5.0, "notes": "MS1/MS2/MS3 microstep select"},
        ],
        "power": {"voltage_v": 12.0, "voltage_tolerance_pct": 100, "current_ma_typical": 800, "current_ma_peak": 2000, "power_source": "external",
                  },
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/A4988_stepper_driver.jpg/640px-A4988_stepper_driver.jpg",
        "datasheet_url": "https://www.pololu.com/file/0J450/A4988.pdf",
        "wiring_diagram_url": "https://lastminuteengineers.com/a4988-stepper-motor-driver-arduino-tutorial/",
        "brand_variants": ["Pololu A4988", "BIQU BIGTREETECH A4988", "Generic StepStick"],
        "price_usd_range": [2, 8],
        "safety_class": "advisory",
    },
    {
        "stable_id": "board.stepper.drv8825",
        "name": "DRV8825 Stepper Motor Driver",
        "vendor": "Texas Instruments",
        "version": "1.0.0",
        "category": "motor_drivers", "subcategory": "stepper",
        "description": "Higher-current upgrade over A4988: up to 45V / 2.2A per phase. 1/32 microstepping. Drop-in replacement on RepRap-style boards. Pair with NEMA 17/23 for 3D printers, CNC, conveyors.",
        "tags": ["stepper", "microstepping", "drv8825", "high-current"],
        "capabilities": ["stepper_drive_bipolar"],
        "interfaces": [
            {"type": "GPIO", "direction": "in", "pins_required": 2, "voltage": 5.0, "notes": "STEP + DIR"},
            {"type": "GPIO", "direction": "in", "pins_required": 3, "voltage": 5.0, "notes": "M0/M1/M2"},
        ],
        "power": {"voltage_v": 24.0, "voltage_tolerance_pct": 90, "current_ma_typical": 1500, "current_ma_peak": 2200, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/DRV8825_stepper_driver.jpg/640px-DRV8825_stepper_driver.jpg",
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/drv8825.pdf",
        "brand_variants": ["Pololu DRV8825", "Polulu #2133", "BIQU DRV8825"],
        "price_usd_range": [3, 10],
        "safety_class": "advisory",
    },
    {
        "stable_id": "board.stepper.tmc2209",
        "name": "TMC2209 Silent Stepper Driver",
        "vendor": "Trinamic / Analog Devices",
        "version": "1.0.0",
        "category": "motor_drivers", "subcategory": "stepper",
        "description": "Ultra-quiet stepper driver with StealthChop2, up to 2A RMS / 2.8A peak. UART-controllable current and microstepping. Standard in modern Klipper 3D printers. Use for low-noise factory floors.",
        "tags": ["stepper", "silent", "tmc", "uart"],
        "capabilities": ["stepper_drive_bipolar"],
        "interfaces": [
            {"type": "GPIO", "direction": "in", "pins_required": 2, "voltage": 5.0, "notes": "STEP + DIR"},
            {"type": "UART", "direction": "bidir", "voltage": 5.0, "notes": "Optional — for runtime current/microstep config"},
        ],
        "power": {"voltage_v": 24.0, "voltage_tolerance_pct": 90, "current_ma_typical": 1700, "current_ma_peak": 2800, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/TMC2209_driver_board.jpg/640px-TMC2209_driver_board.jpg",
        "datasheet_url": "https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2209_Datasheet.pdf",
        "brand_variants": ["BIGTREETECH TMC2209", "Fysetc TMC2209", "Watterott SilentStepStick"],
        "price_usd_range": [5, 15],
        "safety_class": "advisory",
    },
    {
        "stable_id": "board.adc.mcp3008",
        "name": "MCP3008 8-Channel 10-bit ADC (SPI)",
        "vendor": "Microchip",
        "version": "1.0.0",
        "category": "io_expansion", "subcategory": "adc",
        "description": "8-channel 10-bit successive-approximation ADC over SPI. Essential for Raspberry Pi 5 (no built-in ADC) to read photoresistors, potentiometers, analog current sensors.",
        "tags": ["adc", "analog", "spi", "8-channel"],
        "capabilities": ["analog_read"],
        "interfaces": [{"type": "SPI", "direction": "bidir", "voltage": 3.3, "speed_hz": 1350000}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.5, "current_ma_peak": 1, "power_source": "bus"},
        "compute": ["compute.rpi5", "compute.rpi_zero_2_w"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/MCP3008_chip.jpg/640px-MCP3008_chip.jpg",
        "datasheet_url": "https://ww1.microchip.com/downloads/en/DeviceDoc/21295d.pdf",
        "brand_variants": ["Microchip MCP3008-I/P", "Adafruit 856", "Generic breakout"],
        "price_usd_range": [3, 8],
    },
    {
        "stable_id": "board.adc.ads1115",
        "name": "ADS1115 4-Channel 16-bit ADC (I2C)",
        "vendor": "Texas Instruments",
        "version": "1.0.0",
        "category": "io_expansion", "subcategory": "adc",
        "description": "4-channel single-ended (or 2-channel differential) 16-bit ADC over I2C, internal PGA, 860 SPS. Much higher resolution than MCP3008 for low-frequency precision reads (pH probes, load cells).",
        "tags": ["adc", "16-bit", "i2c", "precision"],
        "capabilities": ["analog_read"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x48-0x4B", "speed_hz": 400000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 0.15, "current_ma_peak": 0.3, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/ADS1115_Module.jpg/640px-ADS1115_Module.jpg",
        "datasheet_url": "https://www.ti.com/lit/ds/symlink/ads1115.pdf",
        "brand_variants": ["Adafruit 1085", "Generic GY-ADS1115", "Sparkfun BOB-15334"],
        "price_usd_range": [3, 12],
    },
    {
        "stable_id": "board.io.mcp23017",
        "name": "MCP23017 16-Channel I/O Expander (I2C)",
        "vendor": "Microchip",
        "version": "1.0.0",
        "category": "io_expansion", "subcategory": "gpio_expander",
        "description": "Extends a Pi/Pico's GPIO by 16 pins per chip over I2C; up to 8 chips = 128 pins on one bus. Pull-ups, interrupts, polarity-invert. Standard for button matrices, status LED banks, large-format I/O panels.",
        "tags": ["gpio", "expander", "i2c", "16-channel"],
        "capabilities": ["gpio_read", "gpio_write"],
        "interfaces": [{"type": "I2C", "direction": "bidir", "address": "0x20-0x27", "speed_hz": 1700000, "voltage": 3.3}],
        "power": {"voltage_v": 3.3, "voltage_tolerance_pct": 10, "current_ma_typical": 1, "current_ma_peak": 3, "power_source": "bus"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/MCP23017_breakout.jpg/640px-MCP23017_breakout.jpg",
        "datasheet_url": "https://ww1.microchip.com/downloads/aemDocuments/documents/APID/ProductDocuments/DataSheets/MCP23017-Data-Sheet-DS20001952.pdf",
        "brand_variants": ["Adafruit 5346", "Generic GY-MCP23017", "Pimoroni IO Expander"],
        "price_usd_range": [3, 12],
    },
    {
        "stable_id": "board.relay.8ch_5v",
        "name": "8-Channel 5V Relay Module",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "relays", "subcategory": "multi_channel",
        "description": "Eight opto-isolated 5V relays on one board, 10A 250VAC per channel. Use as a switching panel for multi-zone heaters, lighting circuits, irrigation manifolds.",
        "tags": ["relay", "8-channel", "mains", "opto-isolated"],
        "capabilities": ["switch_load"],
        "interfaces": [{"type": "GPIO", "direction": "in", "pins_required": 8, "voltage": 3.3, "notes": "Active-low control"}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 320, "current_ma_peak": 560, "power_source": "external"},
        "compute": ["compute.pico2w", "compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Relay-module-5v-8ch.jpg/640px-Relay-module-5v-8ch.jpg",
        "brand_variants": ["SunFounder SHIELD-8CH", "ELEGOO 8 Channel Relay", "SainSmart 8-CH"],
        "price_usd_range": [8, 25],
        "safety_class": "critical",
    },
    {
        "stable_id": "board.relay.16ch_5v",
        "name": "16-Channel 5V Relay Module",
        "vendor": "Generic",
        "version": "1.0.0",
        "category": "relays", "subcategory": "multi_channel",
        "description": "Sixteen relays for high-channel-count switching panels. Pair with an MCP23017 expander to avoid eating 16 GPIOs. Use for large-format alarm panels, theatrical lighting, multi-zone HVAC.",
        "tags": ["relay", "16-channel", "mains"],
        "capabilities": ["switch_load"],
        "interfaces": [{"type": "GPIO", "direction": "in", "pins_required": 16, "voltage": 3.3, "notes": "Pair with MCP23017 to cut GPIO usage"}],
        "power": {"voltage_v": 5.0, "voltage_tolerance_pct": 10, "current_ma_typical": 640, "current_ma_peak": 1100, "power_source": "external"},
        "compute": ["compute.rpi5"],
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Relay-module-5v-16ch.jpg/640px-Relay-module-5v-16ch.jpg",
        "brand_variants": ["SainSmart 16-CH", "ELEGOO 16 Channel Relay"],
        "price_usd_range": [15, 40],
        "safety_class": "critical",
    },
]


# ─── Renderer ───────────────────────────────────────────────────────────────
def _manifest_components(c: dict) -> dict:
    """Inflate the shorthand dict into a full schema-valid manifest."""
    meta = {
        "image_url": c.get("image_url"),
        "datasheet_url": c.get("datasheet_url"),
        "wiring_diagram_url": c.get("wiring_diagram_url"),
        "brand_variants": c.get("brand_variants", []),
        "price_usd_range": c.get("price_usd_range"),
        "source": "tools/seed_catalog.py",
    }
    meta = {k: v for k, v in meta.items() if v is not None}
    drivers = c.get("drivers_micropython", [])
    return {
        "stable_id": c["stable_id"],
        "name": c["name"],
        "vendor": c["vendor"],
        "version": c["version"],
        "library": "components_library",
        "category": c["category"],
        "subcategory": c.get("subcategory"),
        "description": c["description"],
        "tags": c.get("tags", []),
        "capabilities": c["capabilities"],
        "dependencies": [],
        "interfaces": c["interfaces"],
        "power": c["power"],
        "safety_class": c.get("safety_class", "advisory"),
        "drivers": [{"runtime": "micropython", "module": d["module"], "version_range": d["version_range"]} for d in drivers],
        "self_tests": [{
            "id": "presence",
            "name": f"{c['name']} reachable",
            "blocking": False,
            "steps": ["read once", "expect no driver error"],
            "expected": "no error",
        }],
        "compatibility": {
            "compute": c.get("compute", []),
            "twin_controls": [],
        },
        "metadata": meta,
    }


def _manifest_board(b: dict) -> dict:
    m = _manifest_components(b)
    m["library"] = "control_board_library"
    return m


def _write(target_dir: Path, manifest: dict) -> bool:
    target_dir.mkdir(parents=True, exist_ok=True)
    p = target_dir / f"{manifest['stable_id']}.json"
    if p.exists():
        return False
    # Strip optional None fields the schema doesn't allow.
    clean = {k: v for k, v in manifest.items() if v not in (None, "")}
    p.write_text(json.dumps(clean, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return True


def main() -> int:
    written = 0
    skipped = 0
    for c in COMPONENTS:
        if _write(COMPONENTS_DIR, _manifest_components(c)):
            written += 1
            print(f"  + components_library/{c['stable_id']}")
        else:
            skipped += 1
    for b in BOARDS:
        if _write(BOARDS_DIR, _manifest_board(b)):
            written += 1
            print(f"  + control_board_library/{b['stable_id']}")
        else:
            skipped += 1
    print(f"\nWrote {written} new manifests, skipped {skipped} existing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
